// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiUnRSAX-GNpICX4LtCIO8QxgO-vWgqMY',
    appId: '1:1039109063599:web:27112fc20a00749c0ce55a',
    messagingSenderId: '1039109063599',
    projectId: 'mymapp-379908',
    authDomain: 'mymapp-379908.firebaseapp.com',
    storageBucket: 'mymapp-379908.appspot.com',
    measurementId: 'G-XFRWZW2SG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeUQmw5KH3JMarWD8L5TY-2Mj88vYYyYM',
    appId: '1:1039109063599:android:4a7cd61781e1ae1c0ce55a',
    messagingSenderId: '1039109063599',
    projectId: 'mymapp-379908',
    storageBucket: 'mymapp-379908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFa4r1bl_zTEcRbeVZqIH1W_S7Pnm54g',
    appId: '1:1039109063599:ios:fd04475d9fc50b770ce55a',
    messagingSenderId: '1039109063599',
    projectId: 'mymapp-379908',
    storageBucket: 'mymapp-379908.appspot.com',
    androidClientId: '1039109063599-eb1t221cqdq6pu7cjisku5elpiv6p4gh.apps.googleusercontent.com',
    iosClientId: '1039109063599-g3stnlk08cic1hc0mo10r9t691blk203.apps.googleusercontent.com',
    iosBundleId: 'com.sbk.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOFa4r1bl_zTEcRbeVZqIH1W_S7Pnm54g',
    appId: '1:1039109063599:ios:fd04475d9fc50b770ce55a',
    messagingSenderId: '1039109063599',
    projectId: 'mymapp-379908',
    storageBucket: 'mymapp-379908.appspot.com',
    androidClientId: '1039109063599-eb1t221cqdq6pu7cjisku5elpiv6p4gh.apps.googleusercontent.com',
    iosClientId: '1039109063599-g3stnlk08cic1hc0mo10r9t691blk203.apps.googleusercontent.com',
    iosBundleId: 'com.sbk.newProject',
  );
}
